# Programming Assignment 2

In [6]:
import numpy as np

### 1. NORMALIZATION Problem

Create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

In [22]:
X = np.array([(9,50,36,27,38),(20,30,1,3,10),(39,49,46,31,9),(1,43,41,18,26),(35,41,24,19,19)])

Xmean = X.mean()
Xstd = X.std()

X_normalized = (X - Xmean) / Xstd

print("X =", X)
print("X_normalized =", X_normalized)

X = [[ 9 50 36 27 38]
 [20 30  1  3 10]
 [39 49 46 31  9]
 [ 1 43 41 18 26]
 [35 41 24 19 19]]
X_normalized = [[-1.17742216  1.56543629  0.62885047  0.02675959  0.76264845]
 [-0.44153331  0.22745655 -1.71261406 -1.57881608 -1.11052318]
 [ 0.82954743  1.4985373   1.29784034  0.29435554 -1.17742216]
 [-1.71261406  1.09714338  0.96334541 -0.57533128 -0.04013939]
 [ 0.56195149  0.96334541 -0.17393737 -0.5084323  -0.5084323 ]]


### 2. DIVISIBLE BY 3 Problem

Create the following 10 x 10 ndarray, which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [12]:
numbers = np.arange(1, 101)
squares = numbers ** 2

A = squares.reshape(10, 10)

div_by_3 = A[A % 3 == 0]

print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


##### CODED BY: AFIDCHAO, DANIELLE TAYLAN OF 2ECE-A

##### SUBMITTED TO: MDM. MA MADECHEEN PANGALIMAN