# Programming Assignment 2

In [4]:
import numpy as np

### 1. NORMALIZATION Problem

Create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

#### Version 1: Established Array

In [6]:
X = np.array([(9,50,36,27,38),(20,30,1,3,10),(39,49,46,31,9),(1,43,41,18,26),(35,41,24,19,19)])

Xmean = X.mean()
Xstd = X.std()

X_normalized = (X - Xmean) / Xstd

print("X =", X)
print("X_normalized =", X_normalized)

X = [[ 9 50 36 27 38]
 [20 30  1  3 10]
 [39 49 46 31  9]
 [ 1 43 41 18 26]
 [35 41 24 19 19]]
X_normalized = [[-1.17742216  1.56543629  0.62885047  0.02675959  0.76264845]
 [-0.44153331  0.22745655 -1.71261406 -1.57881608 -1.11052318]
 [ 0.82954743  1.4985373   1.29784034  0.29435554 -1.17742216]
 [-1.71261406  1.09714338  0.96334541 -0.57533128 -0.04013939]
 [ 0.56195149  0.96334541 -0.17393737 -0.5084323  -0.5084323 ]]


#### Version 2: Random Array Per Entry

In [8]:
X = np.random.rand(5, 5)

X_int = (X * 100).astype(int)

X_normalized = ((X - np.min(X)) / (np.max(X) - np.min(X)) * 100)

print("X :\n", X_int)
print("\nX_normalized:\n", X_normalized)

X :
 [[45  4 61 96 16]
 [84 26 78 89 52]
 [ 0 38 38  6 39]
 [35  9 66 40  9]
 [ 5  5 49 59 77]]

X_normalized:
 [[ 46.24465815   4.08418728  63.47907808 100.          16.22486075]
 [ 86.97660748  26.27825032  80.99567676  91.88842688  53.91240751]
 [  0.          39.43484756  38.93260969   5.57621192  39.84894474]
 [ 35.86916648   8.60265398  68.56536787  41.46316957   8.84739876]
 [  5.09763219   4.82187037  51.0679669   60.77599637  79.46079873]]


#### Version 3: Random Entry Per Entry with (User-Input) Range

In [13]:
low = int(input("Numbers can't go lower than: "))
high = int(input("Numbers can't go higher than: "))

X = np.random.randint(low, high + 1, (5, 5))

X_normalized = (X - np.min(X)) / (np.max(X) - np.min(X))

print("\nX:\n", X)
print("\nX_normalized:\n", X_normalized)

Numbers can't go lower than:  10
Numbers can't go higher than:  50



X:
 [[16 14 30 35 13]
 [12 17 42 11 16]
 [44 50 43 19 18]
 [33 39 42 11 21]
 [48 26 48 16 47]]

X_normalized:
 [[0.12820513 0.07692308 0.48717949 0.61538462 0.05128205]
 [0.02564103 0.15384615 0.79487179 0.         0.12820513]
 [0.84615385 1.         0.82051282 0.20512821 0.17948718]
 [0.56410256 0.71794872 0.79487179 0.         0.25641026]
 [0.94871795 0.38461538 0.94871795 0.12820513 0.92307692]]


### 2. DIVISIBLE BY 3 Problem

Create the following 10 x 10 ndarray, which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [12]:
numbers = np.arange(1, 101)
squares = numbers ** 2

A = squares.reshape(10, 10)

div_by_3 = A[A % 3 == 0]

print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


##### CODED BY: AFIDCHAO, DANIELLE TAYLAN OF 2ECE-A

##### SUBMITTED TO: MDM. MA MADECHEEN PANGALIMAN