# Programming Assignment 2.1

### The Normalization Problem

Create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

In [4]:
import numpy as np

#### Version 1: Established Array

In [7]:
X = np.array([(9,50,36,27,38),(20,30,1,3,10),(39,49,46,31,9),(1,43,41,18,26),(35,41,24,19,19)])

Xmean = X.mean()
Xstd = X.std()

X_normalized = (X - Xmean) / Xstd

print("X =\n", X)
print("X_normalized =\n", X_normalized)

X =
 [[ 9 50 36 27 38]
 [20 30  1  3 10]
 [39 49 46 31  9]
 [ 1 43 41 18 26]
 [35 41 24 19 19]]
X_normalized =
 [[-1.17742216  1.56543629  0.62885047  0.02675959  0.76264845]
 [-0.44153331  0.22745655 -1.71261406 -1.57881608 -1.11052318]
 [ 0.82954743  1.4985373   1.29784034  0.29435554 -1.17742216]
 [-1.71261406  1.09714338  0.96334541 -0.57533128 -0.04013939]
 [ 0.56195149  0.96334541 -0.17393737 -0.5084323  -0.5084323 ]]


#### Version 2: Random Array Input at Every Entry

In [10]:
X = np.random.rand(5, 5)

X_int = (X * 100).astype(int)

X_normalized = ((X - np.min(X)) / (np.max(X) - np.min(X)) * 100)

print("X :\n", X_int)
print("\nX_normalized:\n", X_normalized)

X :
 [[76 72 20 93 68]
 [32 16 87  2 82]
 [39 13 95 34 15]
 [52 32 95 65 26]
 [50 67 86 35 70]]

X_normalized:
 [[ 78.96513073  75.15663365  19.53141732  98.03614791  71.27360841]
 [ 32.64522506  15.04199597  90.96163651   0.          85.68163971]
 [ 39.91979228  12.37259739 100.          34.1454083   14.33572302]
 [ 54.27488899  32.97758858  99.40446731  68.15913904  25.63252785]
 [ 51.50442182  69.57998946  90.27386121  35.65130662  72.72810676]]


#### Version 3: Random Array Input at Every Entry with (User Input) Range

In [13]:
low = int(input("Numbers can't go lower than: "))
high = int(input("Numbers can't go higher than: "))

X = np.random.randint(low, high + 1, (5, 5))

X_normalized = (X - np.min(X)) / (np.max(X) - np.min(X))

print("\nX:\n", X)
print("\nX_normalized:\n", X_normalized)

Numbers can't go lower than:  10
Numbers can't go higher than:  50



X:
 [[21 44 35 34 12]
 [18 40 10 33 41]
 [21 49 44 30 33]
 [41 28 28 43 48]
 [28 16 13 26 49]]

X_normalized:
 [[0.28205128 0.87179487 0.64102564 0.61538462 0.05128205]
 [0.20512821 0.76923077 0.         0.58974359 0.79487179]
 [0.28205128 1.         0.87179487 0.51282051 0.58974359]
 [0.79487179 0.46153846 0.46153846 0.84615385 0.97435897]
 [0.46153846 0.15384615 0.07692308 0.41025641 1.        ]]
